### ISSUE TITLE
[StationStorage] A substorage call is missing

### ISSUE THREAD

**Issue by indydedeken** [Phyks/VelibFxos#65]
The `LocalStationStorage` class don't have an `isLoaded()` medthod. It prevents `recLoadSubstorage` _from StationStorageAdapter_, to use all substorages.

That's why : 
1. `AutorityStationStorage` is not called, 
2. and Stations are not provide in camlCase.

To solve this, we should implement an `isLoaded` function in `LocalStationStorage` like : 

<pre>
api.isLoaded = function() {
    // do something
    return;
};</pre>

**Comment by indydedeken** [comment]
I suggest to use :

<pre>
var LocalStationStorage = function() {
   api.stations = null;
  
   ...
   
   api.isLoaded = function() {
        return api.stations !== null;
   };
  
   ...
};</pre>

**Comment by eliemichel** [comment]
The line `var api = StationStorage();` at the beginning of `LocalStationStorage` has it "inherit" in some way of `StationStorage`'s `isLoaded()` and so has the same behavior, which is to check whether `api.stations` is `null`.

Actually I think that your problem is that your local storage kept old data, from previous calls older than this nex design.

The solution would be to call `localStorage.setItem('lastStationsUpdate', 0)` in the dev tools console to reinit your `localStorage`.

**Comment by indydedeken** [comment]
Right
